import libs = fmt%lib{fmt}



if($config.fmt.enable_modules)
{
    ./ : exe{driver-modules} : {cxx}{driver-modules} hxx{tests.inl} $libs testscript{**}
}
else
{
    ./ : exe{driver} : {cxx}{driver} hxx{tests.inl} $libs testscript{**}
}

