int_libs = # Interface dependencies.
imp_libs = # Implementation dependencies.
#import imp_libs += libhello%lib{hello}

./ : lib{fmt}

lib{fmt}: include/hxx{**} hxx{version} $imp_libs $int_libs
lib{fmt}: src/mxx{fmt} : include = ($config.fmt.enable_modules == true)
lib{fmt}: src/cxx{** -fmt} : include = ($config.fmt.enable_modules == false)

# Include the generated version header into the distribution (so that we don't
# pick up an installed one) and don't remove it when cleaning in src (so that
# clean results in a state identical to distributed).
#
hxx{version} : in{version} $src_root/manifest
{
  dist  = true
  clean = ($src_root != $out_root)
  install = include/fmt
}

# Build options.
#
cxx.poptions =+ "-I$src_base/include" "-I$out_root" "-I$src_root"
objs{*}: cxx.poptions += -DFMT_EXPORT -DFMT_SHARED

# Export options.
#
lib{fmt}:
{
  cxx.export.poptions = "-I$src_base/include" "-I$out_root" "-I$src_root"
  cxx.export.libs = $int_libs
}

libs{fmt}: cxx.export.poptions += -DFMT_SHARED


# For pre-releases use the complete version to make sure they cannot be used
# in place of another pre-release or the final version. See the version module
# for details on the version.* variable values.
#
if $version.pre_release
  lib{fmt}: bin.lib.version = @"-$version.project_id"
else
  lib{fmt}: bin.lib.version = @"-$version.major.$version.minor"

# Install into the fmt/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
include/
{
  {hxx ixx txx}{*}:
  {
    install         = include/
    install.subdirs = true
  }
}
